# Generated by Django 3.1.5 on 2021-01-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchcard', '0002_auto_20210118_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
